import sys
sys.stdout.reconfigure(encoding="utf-8")
content = open("pages/index.js", encoding="utf-8").read()

# Fix thead - mover NIP y Link despues de Torneo
old_thead = '                <thead><tr>\n                  <th>Nombre</th>\n                  <th>NIP</th>\n                  <th>Link</th>\n                  {PHASES.map(p=><th key={p.key}>{t.phases[p.key].split(" ")[0]}</th>)}\n                  <th>Torneo</th><th></th>\n                </tr></thead>'
new_thead = '                <thead><tr>\n                  <th>Nombre</th>\n                  {PHASES.map(p=><th key={p.key}>{t.phases[p.key].split(" ")[0]}</th>)}\n                  <th>Torneo</th>\n                  <th>NIP</th>\n                  <th>Link</th>\n                  <th></th>\n                </tr></thead>'
print("Fix thead:", "OK" if old_thead in content else "NO ENCONTRADO")
content = content.replace(old_thead, new_thead)

# Fix tbody - mover checkboxes primero, luego NIP y Link
old_tbody = '                    <td style={{fontFamily:"var(--fd)",fontSize:"14px"}}>{p.name}</td>\n                    {[...PHASES.map(x=>x.key),"torneo"].map(k=>(\n                      <td key={k}><input type="checkbox" checked={!!p.payments[k]} onChange={()=>togglePay(p.id,k)}/></td>\n                    ))}\n                    <td>\n                      <input\n                        type="text" maxLength={4}\n                        key={`nip-${p.id}`}\n                        defaultValue={p.nip||"1234"}\n                        onBlur={e=>upd(s=>({...s,participants:s.participants.map(x=>x.id===p.id?{...x,nip:e.target.value.replace(/\\D/g,"")}:x)}))}\n                        style={{width:52,textAlign:"center",padding:"3px 6px",fontSize:13}}\n                      />\n                    </td>\n                    <td>\n                      <button\n                        onClick={()=>{\n                          const url=`${window.location.origin}/p/${p.id}`;\n                          navigator.clipboard.writeText(url);\n                          toast2("Link copiado");\n                        }}\n                        style={{padding:"3px 8px",fontSize:11}}\n                        title="Copiar link"\n                      >\n                        Link\n                      </button>\n                    </td>\n                    <td><button className="danger" onClick={()=>removeP(p.id)} style={{padding:"3px 7px"}}><Trash2 size={11}/></button></td>'

new_tbody = '                    <td style={{fontFamily:"var(--fd)",fontSize:"14px"}}>{p.name}</td>\n                    {[...PHASES.map(x=>x.key),"torneo"].map(k=>(\n                      <td key={k}><input type="checkbox" checked={!!p.payments[k]} onChange={()=>togglePay(p.id,k)}/></td>\n                    ))}\n                    <td>\n                      <input\n                        type="text" maxLength={4}\n                        key={`nip-${p.id}`}\n                        defaultValue={p.nip||"1234"}\n                        onBlur={e=>upd(s=>({...s,participants:s.participants.map(x=>x.id===p.id?{...x,nip:e.target.value.replace(/\\D/g,"")}:x)}))}\n                        style={{width:52,textAlign:"center",padding:"3px 6px",fontSize:13}}\n                      />\n                    </td>\n                    <td>\n                      <button\n                        onClick={()=>{\n                          const url=`${window.location.origin}/p/${p.id}`;\n                          navigator.clipboard.writeText(url);\n                          toast2("Link copiado");\n                        }}\n                        style={{padding:"3px 8px",fontSize:11}}\n                        title="Copiar link"\n                      >\n                        \uD83D\uDD17\n                      </button>\n                    </td>\n                    <td><button className="danger" onClick={()=>removeP(p.id)} style={{padding:"3px 7px"}}><Trash2 size={11}/></button></td>'

print("Fix tbody:", "OK" if old_tbody in content else "NO ENCONTRADO")
content = content.replace(old_tbody, new_tbody)

open("pages/index.js", "w", encoding="utf-8").write(content)
